2018-09-01 22:49:43,314 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 4744457ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 01:41:08,515 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 10245121ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 03:29:14,705 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 6485254ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 05:17:18,295 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 6483509ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 07:05:23,214 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 6484866ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 07:16:12,413 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 649042ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 09:04:17,453 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 6484640ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 09:31:35,482 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 1637638ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 11:15:42,665 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 2251104ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 13:51:28,307 ERROR 6914 nodejs.ClusterClientNoResponseError: client no response in 9345562ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 6914
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 15:10:31,981 ERROR 1288 [-/::1/-/9ms GET /] nodejs.TypeError: this.ctx.service.list.find is not a function
    at HomeController.index (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/home.js:7:46)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 1288
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 15:12:56,943 ERROR 1316 [-/::1/-/10ms GET /] nodejs.TypeError: ctx.service.list.find is not a function
    at HomeController.index (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/home.js:8:41)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 1316
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 15:13:47,708 ERROR 1316 [-/::1/-/2ms GET /] nodejs.TypeError: ctx.service.list.find is not a function
    at HomeController.index (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/home.js:8:41)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 1316
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 16:27:01,051 ERROR 1287 nodejs.ClusterClientNoResponseError: client no response in 1374395ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 1287
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 18:00:29,131 ERROR 1287 nodejs.ClusterClientNoResponseError: client no response in 1137983ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 1287
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 18:36:38,118 ERROR 1287 nodejs.ClusterClientNoResponseError: client no response in 808738ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 1287
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 18:38:56,139 ERROR 1287 nodejs.ClusterClientNoResponseError: client no response in 98003ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 1287
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-02 23:50:39,621 ERROR 1287 nodejs.ClusterClientNoResponseError: client no response in 10850250ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 1287
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-03 01:38:58,475 ERROR 1287 nodejs.ClusterClientNoResponseError: client no response in 6478565ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 1287
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-03 03:50:44,455 ERROR 1287 nodejs.ClusterClientNoResponseError: client no response in 7905826ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 1287
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-03 05:52:30,358 ERROR 1287 nodejs.ClusterClientNoResponseError: client no response in 7285729ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 1287
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-03 06:37:40,299 ERROR 1287 nodejs.ClusterClientNoResponseError: client no response in 2688753ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 1287
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 11:25:25,878 ERROR 15296 [-/127.0.0.1/-/8ms GET /] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table 'wetime.list' doesn't exist
    at Query.Sequence._packetToError (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Pool.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:65:19)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:54:5
    sql: SELECT * FROM `list` WHERE `id` = 1 LIMIT 0, 1
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table 'wetime.list' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT * FROM `list` WHERE `id` = 1 LIMIT 0, 1"
name: "ER_NO_SUCH_TABLEError"
pid: 15296
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 11:35:32,182 ERROR 15408 [-/127.0.0.1/-/11ms GET /] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.index (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/home.js:8:41)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 15408
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 11:35:33,480 ERROR 15408 [-/127.0.0.1/-/1ms GET /] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.index (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/home.js:8:41)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 15408
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 11:35:34,266 ERROR 15408 [-/127.0.0.1/-/1ms GET /] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.index (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/home.js:8:41)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 15408
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 11:35:34,828 ERROR 15408 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: Cannot read property 'find' of undefined
    at HomeController.index (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/home.js:8:41)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 15408
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 12:41:11,864 ERROR 15495 nodejs.ClusterClientNoResponseError: client no response in 2327393ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 15495
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 13:01:45,190 ERROR 15495 nodejs.ClusterClientNoResponseError: client no response in 1193316ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 15495
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 13:06:53,662 ERROR 15495 nodejs.ClusterClientNoResponseError: client no response in 188420ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 15495
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 14:44:35,000 ERROR 15495 nodejs.ClusterClientNoResponseError: client no response in 117627ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 15495
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:49:08,801 ERROR 18045 [-/127.0.0.1/-/10ms GET /wetimeios?page_num=1&&page_size=5] nodejs.ReferenceError: res is not defined
    at IosListController.getIosList (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:15:50)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 18045
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:49:39,379 ERROR 18056 [-/127.0.0.1/-/14ms GET /wetimeios?page_num=1&&page_size=5] nodejs.TypeError: Cannot read property 'res' of undefined
    at IosListController.getIosList (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:14:27)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 18056
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:52:14,798 ERROR 18068 [-/127.0.0.1/-/10ms GET /wetimeios?page_num=1&&page_size=5] nodejs.TypeError: Cannot read property 'pageNum' of undefined
    at ListService.fetch (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/service/ioslist.js:11:62)
    at IosListController.getIosList (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:15:44)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 18068
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:52:40,604 ERROR 18103 [-/127.0.0.1/-/8ms GET /wetimeios?page_num=1&&page_size=5] nodejs.TypeError: Cannot read property 'pageNum' of undefined
    at ListService.fetch (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/service/ioslist.js:11:62)
    at IosListController.getIosList (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:15:44)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 18103
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:53:47,494 ERROR 18103 [-/127.0.0.1/-/1ms GET /wetimeios?page_num=1&&page_size=5] nodejs.TypeError: Cannot read property 'pageNum' of undefined
    at ListService.fetch (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/service/ioslist.js:11:62)
    at IosListController.getIosList (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:15:44)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 18103
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:53:48,699 ERROR 18103 [-/127.0.0.1/-/0ms GET /wetimeios?page_num=1&&page_size=5] nodejs.TypeError: Cannot read property 'pageNum' of undefined
    at ListService.fetch (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/service/ioslist.js:11:62)
    at IosListController.getIosList (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:15:44)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 18103
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:53:49,434 ERROR 18103 [-/127.0.0.1/-/1ms GET /wetimeios?page_num=1&&page_size=5] nodejs.TypeError: Cannot read property 'pageNum' of undefined
    at ListService.fetch (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/service/ioslist.js:11:62)
    at IosListController.getIosList (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:15:44)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 18103
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:55:26,145 ERROR 18139 [-/127.0.0.1/-/9ms GET /wetimeios?page_num=1&&page_size=5] nodejs.ReferenceError: condition is not defined
    at ListService.fetch (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/service/ioslist.js:13:47)
    at IosListController.getIosList (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:15:44)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)

pid: 18139
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:55:49,373 ERROR 18146 [-/127.0.0.1/-/7ms GET /wetimeios?page_num=1&&page_size=5] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(0, 10)' at line 1
    at Query.Sequence._packetToError (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Pool.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:65:19)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:54:5
    sql: select * from wetimeios limit (0, 10)
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(0, 10)' at line 1"
sqlState: "42000"
index: 0
sql: "select * from wetimeios limit (0, 10)"
name: "ER_PARSE_ERRORError"
pid: 18146
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:56:20,163 ERROR 18159 [-/127.0.0.1/-/9ms GET /wetimeios?page_num=1&page_size=5] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(0, 10)' at line 1
    at Query.Sequence._packetToError (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Pool.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:65:19)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:54:5
    sql: select * from wetimeios limit (0, 10)
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(0, 10)' at line 1"
sqlState: "42000"
index: 0
sql: "select * from wetimeios limit (0, 10)"
name: "ER_PARSE_ERRORError"
pid: 18159
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:56:52,053 ERROR 18175 [-/127.0.0.1/-/13ms GET /wetimeios?page_num=1&page_size=5] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1, 5)' at line 1
    at Query.Sequence._packetToError (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Pool.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:65:19)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:54:5
    sql: select * from wetimeios limit (1, 5)
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1, 5)' at line 1"
sqlState: "42000"
index: 0
sql: "select * from wetimeios limit (1, 5)"
name: "ER_PARSE_ERRORError"
pid: 18175
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:56:53,127 ERROR 18176 [-/127.0.0.1/-/12ms GET /wetimeios?page_num=1&page_size=5] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1, 5)' at line 1
    at Query.Sequence._packetToError (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Pool.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:65:19)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:54:5
    sql: select * from wetimeios limit (1, 5)
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1, 5)' at line 1"
sqlState: "42000"
index: 0
sql: "select * from wetimeios limit (1, 5)"
name: "ER_PARSE_ERRORError"
pid: 18176
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:56:53,757 ERROR 18176 [-/127.0.0.1/-/7ms GET /wetimeios?page_num=1&page_size=5] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1, 5)' at line 1
    at Query.Sequence._packetToError (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Pool.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:65:19)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:54:5
    sql: select * from wetimeios limit (1, 5)
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1, 5)' at line 1"
sqlState: "42000"
index: 0
sql: "select * from wetimeios limit (1, 5)"
name: "ER_PARSE_ERRORError"
pid: 18176
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 16:58:48,284 ERROR 18211 [-/127.0.0.1/-/6ms GET /wetimeios?page_num=1&page_size=5] nodejs.ReferenceError: item is not defined
    at ListService.fetch (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/service/ioslist.js:14:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 18211
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 17:01:09,136 ERROR 18250 [-/127.0.0.1/-/15ms GET /wetimeios?page_num=1&page_size=5] nodejs.ReferenceError: cts is not defined
    at IosListController.getIosList (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:17:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 18250
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 17:48:06,114 ERROR 18581 [-/127.0.0.1/-/17ms GET /wetimeios?page_num=1&page_size=5] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1-1)*5, 5' at line 1
    at Query.Sequence._packetToError (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Pool.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:65:19)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/co/index.js:54:5
    sql: select * from wetimeios limit (1-1)*5, 5
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(1-1)*5, 5' at line 1"
sqlState: "42000"
index: 0
sql: "select * from wetimeios limit (1-1)*5, 5"
name: "ER_PARSE_ERRORError"
pid: 18581
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 18:32:29,069 ERROR 18629 [-/127.0.0.1/-/9ms GET /insertwetimeios] nodejs.TypeError: Cannot read property 'res' of undefined
    at IosListController.insert (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:28:27)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/koa-router/node_modules/koa-compose/index.js:36:12

pid: 18629
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 18:32:54,107 ERROR 18632 [-/127.0.0.1/-/19ms GET /insertwetimeios] nodejs.ReferenceError: res is not defined
    at IosListController.insert (/Users/wuxiaoxiao/Documents/work/wetime-egg/app/controller/ioslist.js:30:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 18632
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 20:18:41,957 ERROR 17788 nodejs.ClusterClientNoResponseError: client no response in 3036156ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 17788
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 22:07:42,888 ERROR 17788 nodejs.ClusterClientNoResponseError: client no response in 6469838ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 17788
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-05 23:57:47,280 ERROR 17788 nodejs.ClusterClientNoResponseError: client no response in 6604161ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 17788
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-06 00:06:44,290 ERROR 17788 nodejs.ClusterClientNoResponseError: client no response in 536269ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 17788
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-06 00:07:57,228 ERROR 17788 nodejs.ClusterClientNoResponseError: client no response in 72801ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 17788
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-06 07:29:13,167 ERROR 17788 nodejs.ClusterClientNoResponseError: client no response in 26475236ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 17788
hostname: wuxiaoxiaodeMacBook-Pro.local

2018-09-06 09:32:23,880 ERROR 17788 nodejs.ClusterClientNoResponseError: client no response in 7369661ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wuxiaoxiao/Documents/work/wetime-egg/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 17788
hostname: wuxiaoxiaodeMacBook-Pro.local

